steps:

  - id: get-kube-config
    dir: hello-cloudbuild
    name: gcr.io/cloud-builders/kubectl
    env:
    - CLOUDSDK_CORE_PROJECT=My First Project
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1
    - KUBECONFIG=/workspace/.kube/config
    args:
       - cluster-info

  - id: update-deploy-tag
    dir: hello-cloudbuild
    name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - images
      - add-tag
      - gcr.io/${PROJECT_ID}/demo:${COMMIT_SHA}
      - gcr.io/${PROJECT_ID}/demo:${TAG_NAME}

  - id: deploy
    dir: hello-cloudbuild
    name: cloudnatived/helm-cloudbuilder
    env:
      - KUBECONFIG=/workspace/.kube/config
    args:
      - helm
      - upgrade
      - --install
      - ${TAG_NAME}-demo
      - --namespace=${TAG_NAME}-demo
      - --values
      - k8s/demo/${TAG_NAME}-values.yaml
      - --set
      - container.image=gcr.io/${PROJECT_ID}/demo
      - --set
      - container.tag=${COMMIT_SHA}
      - ./k8s/demo
